export { default as HomePage } from './HomePage/HomePage.jsx';
export { default as LoginPage } from './LoginPage/LoginPage.jsx';
export { default as RegisterPage } from './RegisterPage/RegisterPage.jsx';
export { default as ProfilePage } from './ProfilePage/ProfilePage.jsx';
export { default as EventDetailsPage } from './EventDetailsPage/EventDetailsPage.jsx';
export { default as CreateEventPage } from './CreateEventPage/CreateEventPage.jsx';
export { default as NotFoundPage } from './NotFoundPage/NotFoundPage.jsx';
export { default as EventsPage } from './EventsPage/EventsPage.jsx';
export { default as SearchResultsPage } from './ResultsPage/ResultsPage.jsx';
